### ISSUE TITLE
find_external unable to handle external dependencies with uncommon version format

### ISSUE THREAD

**Issue by sakubara** [pyrate-build/pyrate-build#4]
### Description

The helper function `find_external` is unable to handle external dependencies with uncommon version format. One such example is OpenSSL. The current version for OpenSSL is `1.0.2j`. 

### Steps to reproduce
1. Use `find_external('openssl')` in the input list for `executable`.

### Expected Result
The resulting binary linked against libssl and libcrypto.

### Actual Behavior
The version parser errors out with the message `VersionError(openssl): unable to parse version string '1.0.2j'`.

### Platform
Archlinux
pyrate 0.2.9
Python 3.5.2
OpenSSL 1.0.2.j-1

**Comment by FredStober** [comment]
Fixed by:
 * commit 4536367da5841a4d9f5dedcb74dac169d65fbb0b that allows to interpret version strings of the form '1.2.3.c'
 * commit b75338af99a4f8df493a4b1b4634009f1404d316 that provides a special version parser for openssl

I also created a new release 0.2.10 with these fixes.

Cheers, Fred

**Comment by sakubara** [comment]
Thank you very much for fixing this issue so fast. Pyrate is a really nice tool and allows to write neat build files. :+1:
